### ISSUE TITLE
Support other file backends

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/recognize#1]

**Comment by szaimen** [comment]
When enabling support for external storage, It would be great if each external storage could only be scannned once by the backgroundjob so that it doesn't need to scan the same storage for each user which will safe a lot of time. Of course, in this case, the app must be able to create the tags for all users that have access to the same storage while only scanning it once...

**Comment by mvhirsch** [comment]
Would it be possible to ignore external storages for now, so recognize will run on local files? I'm currently using local files and remote files - both providing images. But recognizes errors right before getting to the local ones. 

As a workaround we could simply skip remote storages for now, could we?

**Comment by csolisr** [comment]
My current setup uses a shared local folder for all users of Nextcloud, which is mapped as an "external" local folder. Apparently, this means that your plugin will not run at all on this shared folder - is there some way to force the app into accepting at least external local folders in the meanwhile?

**Comment by marcelklehr** [comment]
I managed to have files in an external folder tagged successfully by recognize, so I'm not sure how relevant this issue is anymore.

**Comment by csolisr** [comment]
> I managed to have files in an external folder tagged successfully by recognize, so I'm not sure how relevant this issue is anymore.

Did you have some special configuration added? Local folders mounted through the external tool are still undetected by the tool - is there some debugging option I can use to see why are those folders ignored?

**Comment by marcelklehr** [comment]
@csolisr The occ commands should spit out much more info in the latest release.
