### ISSUE TITLE
Classify background jobs don't seem to be doing anything and queue stays filled up. Manual recognize:classify works.

### ISSUE THREAD

**Issue by Fosnine** [nextcloud/recognize#1030]
### Which version of recognize are you using?

5.0.3

### Enabled Modes

Object recognition, Face recognition, Video recognition

### TensorFlow mode

Normal mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

NextCloudPi 27.0.1

### Which Operating system do you have installed?

Debian 11.8

### Which database are you running Nextcloud on?

MySQL 10.5.21

### How much RAM does your server have?

6GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

When I run recognize:classify manually, everything seems to work correctly and tags show up. I don't have any people even after running cluster manually with the command but that seems to be correct since recognize says:
'Face clustering: 79 faces left to cluster, Last clustering run: 1 hour ago, Scheduled background jobs: 0,
A minimum of 120 faces per user is necessary for clustering to kick in;
Files stay queued after adding them for 2+ days but I don't get any errors. background jobs are scheduled but the amount of queued files isn't going down. When a picture is added, it immediately shows up in the queue.
GUI shows:
'Face recognition: 72 Queued files, Last classification: 1 hour ago, Scheduled background jobs: 1, Last background job execution: 3 minutes ago'
'Object recognition: 72 Queued files, Last classification: 1 hour ago, Scheduled background jobs: 1, Last background job execution: 8 minutes ago'
'Landmark recognition: 27 Queued files, Last classification: never, Scheduled background jobs: 2, Last background job execution: 8 minutes ago'
'Video recognition: 0 Queued files, Last classification: 1 hour ago, Scheduled background jobs: 0,'

The last classification time is when I ran recognize:classify again.

Cron seems to be working correctly since it doesn't show any errors when run manually and debug logs show that other jobs get finished in 0 seconds:

e.g.
[cron] Debug: Finished OCA\Notifications\BackgroundJob\SendNotificationMails job with ID 18 in 0 seconds

at 2023-11-12T16:45:01+00:00

screenshots of oc_jobs table:
![Naamloos](https://github.com/nextcloud/recognize/assets/21237526/20d8a403-b396-40d0-bee7-e8aba7bda708)
![image](https://github.com/nextcloud/recognize/assets/21237526/75169908-6f41-4b93-8d3c-dd22e431154b)

### Expected Behavior

I expect the background jobs to classify when cron runs.

### To Reproduce

1. run recognize:classify to initially classify all photos and videos
2. add pictures or videos to nextcloud
3. queue increases but never gets processed

### Debug log

There are no errors that lead me to believe anything wrong is happening. The only related lines in the logs are the following:

[cron] Debug: Skipping OCA\Recognize\BackgroundJobs\ClassifyLandmarksJob job with ID 4901 because another job with the same class is already running

at 2023-11-12T16:40:02+00:00

[cron] Debug: Skipping OCA\Recognize\BackgroundJobs\ClassifyFacesJob job with ID 4684 because another job with the same class is already running

at 2023-11-12T16:40:02+00:00

[cron] Debug: Skipping OCA\Recognize\BackgroundJobs\ClassifyImagenetJob job with ID 4683 because another job with the same class is already running

at 2023-11-12T16:40:02+00:00

[cron] Debug: Skipping OCA\Recognize\BackgroundJobs\ClassifyLandmarksJob job with ID 4678 because another job with the same class is already running

at 2023-11-12T16:40:02+00:00

**Comment by marianionut** [comment]
I have the same issue with Nextcloud version 27.1 6 and Recognize version 5.0.3, a lot of pictures in my case 133228.

Nextcloud is installed with snap in a VM with 16 GB RAM, OS Ubuntu, kernel, Linux 5.11.0-49-generic x86_64

CPU: Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz (8 cores)

The pictures are mounted from a second internal drive NVMe 4 TB with NTFS and external drive plugin.
```
nextcloud@nextcloud:~$ cat /etc/fstab | grep backup
/dev/sdb2 /media/backup_poze ntfs-3g defaults 0 0
nextcloud@nextcloud:~$ df -h | grep /media
/dev/sdb2                          3.7T  1.2T  2.6T  32% /media/backup_poze
```
I already reset faces ones and re-run the classify job, but it takes a few days to proces all my pictures which are added in the queue. The issue is  the background jobs don't pick up the new faces.
If I manually run the  command occ recognize:cluster-faces =>

Clustering face detections for user x
ClusterDebug: Retrieving face detections for user x
ClusterDebug: Not enough face detections found
Clustering face detections for user y
ClusterDebug: Retrieving face detections for user y
ClusterDebug: Not enough face detections found
root@nextcloud:/home/nextcloud#

It started fine for a few hours and after that just dropped the queue.
