### ISSUE TITLE
Faces with cluster_id NULL

### ISSUE THREAD

**Issue by illnesse** [nextcloud/recognize#442]
What's going to happen with faces that have been removed from clusters, can we maybe get a "Unknown Person" cluster element in Photos/Memories that has all the removed and not yet assigned faces in it?  (so basically all with cluster_id = NULL)

Currently if you delete a face from a cluster (remove from person) it won't show up anywhere in the UI any more, right?

**Comment by marcelklehr** [comment]
> Currently if you delete a face from a cluster (remove from person) it won't show up anywhere in the UI any more, right?

Yes, it's still up for grabs for the next run of the clustering algorithm in case new photos appear with that face.

**Comment by marcelklehr** [comment]
> can we maybe get a "Unknown Person" cluster element 

What would be the use case for this, in your mind?

**Comment by Cebrain** [comment]
Would also like to see a feature for the removed and unassigned faces.

**Comment by bdevy** [comment]
It would be helpful to keep state of people that have been Removed from a cluster and also clusters that have been deleted (maybe soft delete and just hide instead, with the option to view 'hidden' clusters).

There are times when I toggle off and on the Face Recognition feature and in my brief testing this seems to re-find these faces and recreate the deleted clusters.

If a face is Removed from Person, perhaps it could be given a status that prevents it from being added back to that same person.

If a cluster is removed, it would be beneficial to maintain that cluster as hidden so that new images that would get added to that cluster are indeed added to it instead of generating a new cluster. This also then may benefit from a 'review / approve' process to be sure that unintended faces/images aren't added to hidden clusters without ever knowing about it.

**Comment by chrissi5120** [comment]
What would i have to do, to get my ~10k NULL-cluster faces back in queue for reprocessing without nuking anything else?

I often used "remove from person" or even "remove person" to get rid und cluttered/unorganised stuff and continued to clean out the good clusters.

**Comment by marcelklehr** [comment]
>  get my ~10k NULL-cluster faces back in queue for reprocessing without nuking anything else?

They are automatically thrown into the mix whenever a clustering run is done.
