### ISSUE TITLE
Recognize is not cleaning up old tags even if triggered from occ

### ISSUE THREAD

**Issue by galandilias** [nextcloud/recognize#465]
I am using recognize quite long. From version 2.0 or even below. I have huge collection of private photos labelled via recognize. Today I wanted to clean up the whole collection as I see tags like 'Tagged by recognize 2.1.2' or 'Tagged by recognize' and many more which are not getting removed after `occ recognize:reset-tags`. Is there a way to clean them all completely and start over from scratch? Currently recognize seems to be unable to clean tags created by old versions...

I am using nor NC 25.0.1 and Recognize 3.1.2

**Comment by marcelklehr** [comment]
Are only the version tags not getting removed or all tags set on photos with the old version tags?

**Comment by galandilias** [comment]
All the old ones

**Comment by galandilias** [comment]
I have managed to remove them manually - but still could be fixed for the reverse combatibility

**Comment by bdevy** [comment]
> I have managed to remove them manually - but still could be fixed for the reverse combatibility

What method did you use to remove them manually?

**Comment by galandilias** [comment]
`occ:tag delete <id>`

**Comment by GrillGuth** [comment]
I experience the same problem. Adding the old tags from older versions within the reset (and cleanup?) command would be really nice. I think this should be the expected behaviour, right? If not a separate command for it would be helpful as removing 100+ tags manually with the “occ tag:delete [<id>]”-command is quite a pain.
