### ISSUE TITLE
GPU is not being used

### ISSUE THREAD

**Issue by derritter88** [nextcloud/recognize#67]
Hello @marcelklehr ,

I have enabled GPU support at the admin GUI but when I start a manual process via `occ recognize:classify` I can see that a process is being started and using 100 % a CPU core.
The GPU is not being used.

I have installed all the specified Nvidia applications/libraries

**Comment by marcelklehr** [comment]
I'll definitely try to make something available. Currently, my problem is that I have to develop that blindly, as I don't have a GPU machine available.

**Comment by derritter88** [comment]
If you want you can pack me the thing and I will act as your alpha-/beta tester?!

**Comment by debian-user-france1** [comment]
I'm testing it with my NVIDIA GeForce GTX 1660 super

**Comment by marcelklehr** [comment]
> Okay so for the moment I can remove all necessary Nvidia libraries (except driver)?

For the moment no NVIDIA drivers and libraries are needed, but they won't hurt either, so it's up to you.

**Comment by derritter88** [comment]
@marcelklehr just in case of: Windows now supports NVIDIA GPUs within its WSL which I am using.
So if you have any tests which I could do just let me know.

**Comment by bugsyb** [comment]
@derritter88, did you get it working?
I've NC in Docker and have been able to get containers gaining access to GPU, i.e. Tensorflow example:
`docker run --gpus all -it --rm tensorflow/tensorflow:latest-gpu    python -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
`

Similar results get NVIDIA examples:
```
#docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
> Windowed mode
> Simulation data stored in video memory
> Single precision floating point simulation
> 1 Devices used for simulation
GPU Device 0: "Maxwell" with compute capability 5.0

> Compute 5.0 CUDA device: [NVIDIA GeForce GTX 960M]
5120 bodies, total time for 10 iterations: 6.155 ms
= 42.591 billion interactions per second
= 851.816 single-precision GFLOP/s at 20 flops per interaction
```

I've big archive of photos to get processed and running it on CPU is an overkill.

Thanks for hints on how to get it working - am not shy customizing NC container/whatever is needed.

**Comment by derritter88** [comment]
> @derritter88, did you get it working? I've NC in Docker and have been able to get containers gaining access to GPU, i.e. Tensorflow example: `docker run --gpus all -it --rm tensorflow/tensorflow:latest-gpu python -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))" `
> 
> Similar results get NVIDIA examples:
> 
> ```
> #docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
> > Windowed mode
> > Simulation data stored in video memory
> > Single precision floating point simulation
> > 1 Devices used for simulation
> GPU Device 0: "Maxwell" with compute capability 5.0
> 
> > Compute 5.0 CUDA device: [NVIDIA GeForce GTX 960M]
> 5120 bodies, total time for 10 iterations: 6.155 ms
> = 42.591 billion interactions per second
> = 851.816 single-precision GFLOP/s at 20 flops per interaction
> ```
> 
> I've big archive of photos to get processed and running it on CPU is an overkill.
> 
> Thanks for hints on how to get it working - am not shy customizing NC container/whatever is needed.

Hello @bugsyb ,

thanks for sharing this with me/us. Might be a useful information for some people but unfortunately I do not use Nextcloud as a Docker container.
I "just" have a regular dedicated Nextcloud VM.
I also had around ~100k of photos/images to classify but my CPU handled that over the last couple of weeks.

I had some discussions with @marcelklehr about it and the major problem would be to have an AI library like Tensorflow which could handled both Nvidia and AMD GPUs

**Comment by bugsyb** [comment]
Hi @derritter88 ,

Thanks for swift response.

I did take a quick look at what gets installed as part of Recognize and smells like tensorflow-webgl gets there.
There is also flag in the code which suggest it should be possible even today:
`process.env.RECOGNIZE_GPU`

Hopes were that given your earlier engagement you'd know how to get Recognize using GPU. 

I have also large number of photos to be processed and... well, hoped could leverage GPU which is wasted otherwise.

I run most of apps these days as containers, just for simplicity/dependency and easiness of portability between systems. Happy to share knowledge on the side if you'd be interested.

Re GPUs Nvidia and AMD, tensorflow allows to get it run both natively as well as in container, as demonstrated for Nvidia.

Here is small explanation covering AMD:
https://community.amd.com/t5/hsa/tensorflow-with-amd-gpu/td-p/199925
https://medium.com/analytics-vidhya/install-tensorflow-2-for-amd-gpus-87e8d7aeb812
https://www.amd.com/en/technologies/infinity-hub/tensorflow
https://tealfeed.com/install-tensorflow-gpu-amd-gpus-vbs7s

There was also other implementation DirectML, though as Internet claims, it was for Windows and WSL which standard Linux wouldn't count in as to be used (am not sure about the latter though).

If we could get started with Nvidia, which is more popular across people who would use it for Linux (not so much gaming ;) ) it would be great, especially as Tensorflow is already available.

I can't help much with AMD as don't have one.

**Comment by derritter88** [comment]
To be honest: I gave up this topic and passed my GPU to a Plex VM for video transcoding but maybe @marcelklehr could improve the general logic of recognize?

**Comment by Doomsdayrs** [comment]
I have an AMD gpu in a laptop that I use for nextcloud

**Comment by arch-user-france1** [comment]
> I have an AMD gpu in a laptop that I use for nextcloud

AMD GPUs probably won't work anyways.
