### ISSUE TITLE
Performance Setup: Nice Level for node server process

### ISSUE THREAD

**Issue by ralfi** [nextcloud/recognize#734]
### Describe the feature you'd like to request

It would be useful to set a nice level for the node process. Setting up a restriction to a cpu like realized works well on multi core cpus but it seems to me it could be a better solution to fine or granular setup the processes for working in background.

Thanks for your work @marcelklehr!

### Describe the solution you'd like

see above

### Describe alternatives you've considered

see above

**Comment by marcelklehr** [comment]
Good idea!

**Comment by ralfi** [comment]
Hi,

it is possible to set the nice level with a command-line extension like "nice -20 /....../node .../classifier_imagenet.js" for node?

**Comment by arch-user-france1** [comment]
> Hi,
> 
> it is possible to set the nice level with a command-line extension like "nice -20 /....../node .../classifier_imagenet.js" for node?

That should certainly work on AppArmor systems such as Debian, yes. Just do /usr/bin/nice -n 15 ${noce_path} ${script_path}.
Selinux systems may require the `bin_t` bit on /usr/bin/nice, otherwise the execution of the file could be denied, but that depends by the rulesets the php process is regulated.

Better would be setting the niceness within the classification script. Perhaps that may serve this purpose: https://github.com/addaleax/nice-napi

**Comment by marcelklehr** [comment]
- [ ] One setting in admin settings for all models
 - [ ] Add nice call to Classifier.php
