### ISSUE TITLE
Bloats oc_activity table

### ISSUE THREAD

**Issue by tvogel** [nextcloud/recognize#844]
### Which version of recognize are you using?

4.0.1

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

26.0.1

### Which Operating system do you have installed?

Ubuntu 22.04.2 LTS

### Which Docker container are you using to run Nextcloud? (if applicable)

n/a

### How much RAM does your server have?

32 GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

We recently discovered our `oc_activity` table to eat more than 7GB of disk space. Inspection reveals that:

```
MariaDB [<redacted>]> select sum(1), sum(type='systemtags'), sum(type != 'systemtags') from oc_activity where activity_id between 10000000 and 11000000;
+--------+------------------------+---------------------------+
| sum(1) | sum(type='systemtags') | sum(type != 'systemtags') |
+--------+------------------------+---------------------------+
| 987986 |                 987528 |                       458 |
+--------+------------------------+---------------------------+
1 row in set (3.393 sec)
```
The vast majority is `systemtags` modification caused by `recognize` adding/removing an enormous amount of tags, repeated for all `affecteduser`s.

This bloat is unbearable and needs to be mitigated. 

### Expected Behavior

With this amount of tagging categories and users, individual tagging activity recording seems inacceptable, so it should not be done. At least there needs to be a way to opt out.

### To Reproduce

Enable `recognize` on any installation with a relevant number of users and files.

**Comment by marcelklehr** [comment]
Hello,
I'm sorry you are having trouble with recognize. I'm afraid recognize uses the standard approach to tagging in Nextcloud which cannot be changed. Large activity tables are quite a common occurrence with larger installations. If you need help mitigating this, Nextcloud GmbH is happy to help with mission critical installations as part of our Enterprise offering.

**Comment by tvogel** [comment]
Ok, answer tagged as useless.

**Comment by marcelklehr** [comment]
> Ok, answer tagged as useless.

I'm sorry I couldn't be more helpful, but the issue you describe is not a problem with recognize and actually also not a problem with Nextcloud. We have customers with much larger databases that run fine. You did not specify how many users you have, but if you have trouble handling this amount of data on your own I can only point you to our paid support. That's why it exists: So that customers who are large enough to need and afford it can pay us to help them with stuff that  private home users of nextcloud will never run into.

**Comment by tvogel** [comment]
Yes, we can "handle" it and are not looking to buy compute resources. (So, wrong sales channel here.) The problem is wasting resources that could be used for useful things in contrast to logging `number_of_files * number_of_feature_catalog_entries * number_of_users` extremely redundant information in a table that is meant to store simple, concise activities. 
So, your approach to neglect the problem on all levels, is just ignoring very real resource waste issues. Buying more resources in the cloud is no solution to inefficiency. And it's also just the wrong thing to do environmentally. Nextcloud is a relevant player and your waste contributes to overall planet consumption. No thanks to that attitude from my side.

**Comment by marcelklehr** [comment]
Thank you for taking the time to file this issue.

Let me outline again: This issue is out of scope of this repository. Also, Nextcloud GmbH does not sell compute or cloud space, we sell support.

**Comment by vasyugan** [comment]
> > Ok, answer tagged as useless.
> 
> I'm sorry I couldn't be more helpful, but the issue you describe is not a problem with recognize and actually also not a problem with Nextcloud. 

I respectfully disagree. When one wastes a two digit number of gigabytes for no benefit in return, I'd say this clearly is a problem. And specifically it is a problem with recognize, as no other app seems to have a similar effect. The problem isn't just with disk storage wasted but also with recognize hogging the system to the degree of causing periodic timeouts. Since I was curious, I did let it work for some day, but the result was barely usable. In the photos app I see dozens of new tags each of which supposedly contain up to hundreds of photos, yet when I enter them, no photos are being displayed. 

Again, no worries. We solved this by retiring the recognize app. I installed it out of interest, not out of need. Not being able to use it isn't really a big problem. But this app alone seems to triple the resource requirements. This is something I haven't seen in any other major component like Nextcloud Office or, the Nextcloud Talk high performance backend or fulltextsearch, that substantially extend NC's functionality. For now, the cost benefit ratio  of recognize seems to be much worse than in any of those.

**Comment by GretaD** [comment]
Hello @tvogel
We understand that dealing with bugs can be frustrating, but passive-aggressive language is not helpful for anyone, nor is it acceptable as per our code of conduct: https://nextcloud.com/contribute/code-of-conduct/

Thank you,
